#define LEFT 5
#define RIGHT 6

#define LEFT_FORWARD 180
#define LEFT_BACKWARD 0
#define RIGHT_FORWARD 0
#define RIGHT_BACKWARD 180
#define STOP_LEFT 94
#define STOP_RIGHT 95

#define LEFT_TURN_90_DEGREES 930
#define RIGHT_TURN_90_DEGREES 950
